name: ${name}
version: ${version}
main: de.kevin_stefan.virtualChests.VirtualChests
api-version: '1.21.5'
authors: [ Kevin Stefan ]
website: https://modrinth.com/project/virtual-chests
libraries:
  - org.hibernate.orm:hibernate-core:7.0.0.Final
  - org.hibernate.orm:hibernate-c3p0:7.0.0.Final
  - org.hibernate.orm:hibernate-community-dialects:7.0.0.Final
  - dev.dejvokep:boosted-yaml:1.3.7
  - dev.dejvokep:boosted-yaml-spigot:1.4
permissions:
  virtualchests.admin:
    children:
      virtualchests.use: true
  virtualchests.multiple.3:
    children:
      virtualchests.open.1: true
      virtualchests.open.2: true
      virtualchests.open.3: true
  virtualchests.multiple.5:
    children:
      virtualchests.multiple.3: true
      virtualchests.open.4: true
      virtualchests.open.5: true
  virtualchests.multiple.10:
    children:
      virtualchests.multiple.5: true
      virtualchests.open.6: true
      virtualchests.open.7: true
      virtualchests.open.8: true
      virtualchests.open.9: true
      virtualchests.open.10: true
